### ISSUE TITLE
recommended engine: re-order to prioritise vanilla-compatible demo playback

### ISSUE THREAD

**Issue by jmtd** [freedoom/freedoom.github.io#23]
At https://freedoom.github.io/download.html you recommend, in this order

1. gzdoom
2. crispy-doom

However, gzdoom can't play the DEMO lumps in Freedoom. How about prioritising a port that does? I suggest

1. crispy-doom
2. Eternity Engine
3. GZDoom

See also https://github.com/flathub/io.github.Freedoom-Phase-1/issues/5

**Comment by chungy** [comment]
I felt like practicality won out over both port simplicity and demo playback when I played GZDoom at top, which was a conscious decision that people would be most likely to click the first one and use that.

GZDoom's practicality comes in the massive swath of mods that have been released exclusively for it, and pretty much any other choice of port would be more likely to leave newbie players confused about why X mod doesn't work with what they downloaded. And to be frank, I don't think playing back IWAD demos is all that critical to the function of Freedoom. :)

As the commit message in 2df194aca972850f063c7b3f38d9f552c1e24c5d states, I believe that leaving the list with at most two ports is best, instead of overrunning it with too many choices that non-technical people don't know how to decide. I'm not even sure how to explain the unique properties of many ports. What features does Eternity have that would cause a newbie to use it instead of Crispy or GZDoom?

GZDoom and Crispy are quite clearly polar opposites in design philosophy, and the download page mentions that Crispy is more "old school", implying that GZDoom is "modern" -- this is why I thought they were the appropriate ones to list on the download page.  The first one will play the nicest with the full-native resolution of any-aspect monitor you play on. The second one is a bit... crispy... and stuck in 4:3.

**Comment by igdegoo** [comment]
why not prboom?

**Comment by mc776** [comment]
On the one hand, Crispy probably runs on more computers with fewer issues, and a lot of the sort of mods that only work in GZDoom do stuff that's pretty id-specific, so it may be a better starting point.

On the other, ordering them so GZDoom is last while keeping the "minimalist"/"advanced" descriptions gives us this unintentional "virgin Crispy chad GZ" messaging that seems to emphasize GZDoom even more, instead of starting with the big modern noisy thing and moving to the cleaner simpler thing.

I think on the balance it's best to leave it as it is now.

**Comment by mc776** [comment]
How about
1. Crispy
2. GZ
3. Eternity

This gives us the starting base gold standard,* the big wacky kitchen sink everything bagel, and then something that may better strike a reasonable balance between them.

*tbh I'd give Chocolate this status but visplane overflow crashes are scary

**Comment by mc776** [comment]
If we add EE to this page what URL should be used?
